//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FCAppleAccount : NSObject
{
    NSString *_DSID;
    NSString *_userStoreFrontID;
    NSString *_contentStoreFrontID;
}

+ (id)sharedAccount;
+ (id)backingUserDefaultKeys;
@property(copy, nonatomic) NSString *contentStoreFrontID; // @synthesize contentStoreFrontID=_contentStoreFrontID;
@property(copy, nonatomic) NSString *userStoreFrontID; // @synthesize userStoreFrontID=_userStoreFrontID;
@property(copy, nonatomic) NSString *DSID; // @synthesize DSID=_DSID;
- (void).cxx_destruct;
- (void)_setStoreFrontDependentProperties;
- (id)endpointConnectionClientID;
- (id)contentStoreFrontID_US;
- (_Bool)isUserSignedInToiCloud;
- (_Bool)isPrivateDataSyncingEnabled;
- (void)loadStoreFrontIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

