//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FCAsyncSerialQueue, FCCloudContext, FCIAdConfiguration, FCPrefetchConfiguration, FCRecommendedCategory, FCResource, FCTopStoriesConfiguration, NSArray, NSDictionary, NSHashTable, NSMutableArray, NTPBPersonalizationConfig;
@protocol OS_dispatch_queue;

@interface FCAppConfiguration : NSObject
{
    _Bool _forceAppConfigUpdate;
    _Bool _forceTrendingSearchesUpdate;
    NSArray *_hiddenFeedIDs;
    NSArray *_onboardingFeedIDs;
    NSArray *_presubscribedFeedIDs;
    long long _shortReminderTime;
    long long _longReminderTime;
    long long _minimumArticleUpdateInterval;
    long long _initialArticlesFromNewFavorite;
    long long _autoScrollToTopFeedTimeout;
    long long _timeBetweenWidgetInsertions;
    long long _timeBetweenSameWidgetReinsertion;
    long long _numberOfScreenfulsScrolledToBypassWidgetTimeLimit;
    double _batchedFeedTimeout;
    double _interstitialAdLoadDelay;
    double _prerollLoadingTimeout;
    NSDictionary *_endpointConfigsByEnvironment;
    double _tileProminenceScoreBalanceValue;
    long long _minimumDistanceBetweenImageOnTopTiles;
    FCIAdConfiguration *_iAdConfig;
    FCPrefetchConfiguration *_prefetchConfig;
    FCTopStoriesConfiguration *_topStoriesConfig;
    long long _appConfigRefreshRate;
    long long _trendingTopicsRefreshRate;
    NSArray *_trendingTopics;
    long long _articleRapidUpdatesTimeout;
    FCAsyncSerialQueue *_requestSerialQueue;
    NSObject<OS_dispatch_queue> *_accessQueue;
    FCRecommendedCategory *_topLevelCategory;
    NTPBPersonalizationConfig *_personalizationConfig;
    NSDictionary *_personalizationTreatments;
    FCCloudContext *_context;
    NSHashTable *_observers;
    NSMutableArray *_observationBlocks;
    FCResource *_configurationResource;
    FCResource *_trendingSearchesResource;
}

@property(retain, nonatomic) FCResource *trendingSearchesResource; // @synthesize trendingSearchesResource=_trendingSearchesResource;
@property(retain, nonatomic) FCResource *configurationResource; // @synthesize configurationResource=_configurationResource;
@property(retain, nonatomic) NSMutableArray *observationBlocks; // @synthesize observationBlocks=_observationBlocks;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) FCCloudContext *context; // @synthesize context=_context;
@property(retain, nonatomic) NSDictionary *personalizationTreatments; // @synthesize personalizationTreatments=_personalizationTreatments;
@property(retain, nonatomic) NTPBPersonalizationConfig *personalizationConfig; // @synthesize personalizationConfig=_personalizationConfig;
@property(retain, nonatomic) FCRecommendedCategory *topLevelCategory; // @synthesize topLevelCategory=_topLevelCategory;
@property(nonatomic) _Bool forceTrendingSearchesUpdate; // @synthesize forceTrendingSearchesUpdate=_forceTrendingSearchesUpdate;
@property(nonatomic) _Bool forceAppConfigUpdate; // @synthesize forceAppConfigUpdate=_forceAppConfigUpdate;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *accessQueue; // @synthesize accessQueue=_accessQueue;
@property(retain, nonatomic) FCAsyncSerialQueue *requestSerialQueue; // @synthesize requestSerialQueue=_requestSerialQueue;
@property(nonatomic) long long articleRapidUpdatesTimeout; // @synthesize articleRapidUpdatesTimeout=_articleRapidUpdatesTimeout;
@property(readonly, nonatomic) NSArray *trendingTopics; // @synthesize trendingTopics=_trendingTopics;
@property(nonatomic) long long trendingTopicsRefreshRate; // @synthesize trendingTopicsRefreshRate=_trendingTopicsRefreshRate;
@property(nonatomic) long long appConfigRefreshRate; // @synthesize appConfigRefreshRate=_appConfigRefreshRate;
@property(retain, nonatomic) FCTopStoriesConfiguration *topStoriesConfig; // @synthesize topStoriesConfig=_topStoriesConfig;
@property(retain, nonatomic) FCPrefetchConfiguration *prefetchConfig; // @synthesize prefetchConfig=_prefetchConfig;
@property(retain, nonatomic) FCIAdConfiguration *iAdConfig; // @synthesize iAdConfig=_iAdConfig;
@property(nonatomic) long long minimumDistanceBetweenImageOnTopTiles; // @synthesize minimumDistanceBetweenImageOnTopTiles=_minimumDistanceBetweenImageOnTopTiles;
@property(nonatomic) double tileProminenceScoreBalanceValue; // @synthesize tileProminenceScoreBalanceValue=_tileProminenceScoreBalanceValue;
@property(retain, nonatomic) NSDictionary *endpointConfigsByEnvironment; // @synthesize endpointConfigsByEnvironment=_endpointConfigsByEnvironment;
@property(nonatomic) double prerollLoadingTimeout; // @synthesize prerollLoadingTimeout=_prerollLoadingTimeout;
@property(nonatomic) double interstitialAdLoadDelay; // @synthesize interstitialAdLoadDelay=_interstitialAdLoadDelay;
@property(nonatomic) double batchedFeedTimeout; // @synthesize batchedFeedTimeout=_batchedFeedTimeout;
@property(nonatomic) long long numberOfScreenfulsScrolledToBypassWidgetTimeLimit; // @synthesize numberOfScreenfulsScrolledToBypassWidgetTimeLimit=_numberOfScreenfulsScrolledToBypassWidgetTimeLimit;
@property(nonatomic) long long timeBetweenSameWidgetReinsertion; // @synthesize timeBetweenSameWidgetReinsertion=_timeBetweenSameWidgetReinsertion;
@property(nonatomic) long long timeBetweenWidgetInsertions; // @synthesize timeBetweenWidgetInsertions=_timeBetweenWidgetInsertions;
@property(nonatomic) long long autoScrollToTopFeedTimeout; // @synthesize autoScrollToTopFeedTimeout=_autoScrollToTopFeedTimeout;
@property(nonatomic) long long initialArticlesFromNewFavorite; // @synthesize initialArticlesFromNewFavorite=_initialArticlesFromNewFavorite;
@property(nonatomic) long long minimumArticleUpdateInterval; // @synthesize minimumArticleUpdateInterval=_minimumArticleUpdateInterval;
@property(nonatomic) long long longReminderTime; // @synthesize longReminderTime=_longReminderTime;
@property(nonatomic) long long shortReminderTime; // @synthesize shortReminderTime=_shortReminderTime;
@property(retain, nonatomic) NSArray *presubscribedFeedIDs; // @synthesize presubscribedFeedIDs=_presubscribedFeedIDs;
@property(retain, nonatomic) NSArray *onboardingFeedIDs; // @synthesize onboardingFeedIDs=_onboardingFeedIDs;
@property(retain, nonatomic) NSArray *hiddenFeedIDs; // @synthesize hiddenFeedIDs=_hiddenFeedIDs;
- (void).cxx_destruct;
- (void)_didChangeTrendingTopics;
- (void)_didChange;
- (id)_languageConfigurationsInProtobufTrendingConfiguration:(id)arg1 forLanguages:(id)arg2;
- (id)_languageConfigurationsInProtobufConfiguration:(id)arg1 forLanguages:(id)arg2;
- (id)_preferredLanguages;
- (void)_extractTrendingTopicsFromProtobufConfiguration:(id)arg1;
- (void)_extractTopStoriesFromProtobufConfiguration:(id)arg1;
- (void)_extractPrefetchConfigFromProtobufConfiguration:(id)arg1;
- (void)_extractiAdConfigFromProtobufConfiguration:(id)arg1;
- (void)_extractPersonalizationConfigFromProtobufConfiguration:(id)arg1;
- (id)_categoryFromProtobufCategory:(id)arg1;
- (void)_extractTopLevelCategoryFromProtobufConfiguration:(id)arg1;
- (void)_extractFeedIDsFromProtobufConfiguration:(id)arg1;
- (void)_extractEndpointConfigurationFromProtobufConfiguration:(id)arg1;
- (void)_extractCommonValuesFromProtobufConfiguration:(id)arg1;
- (void)_processTrendingSearchesData:(id)arg1;
- (void)_processConfigurationData:(id)arg1;
- (void)_fetchTrendingSearchesForStoreFrontID:(id)arg1 cachePolicy:(unsigned long long)arg2 completionQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_fetchAppConfigurationForStoreFrontID:(id)arg1 cachePolicy:(unsigned long long)arg2 refreshRate:(double)arg3 completionQueue:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)forceUpdateOnNextLaunch;
- (void)addChangeObservationBlock:(CDUnknownBlockType)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)fetchTrendingSearchesIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchAppConfigurationIfNeededWithCompletionQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchAppConfigurationIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (long long)personalizationTreatmentIDForFeldsparID:(id)arg1;
- (id)personalizationTreatmentForFeldsparID:(id)arg1;
@property(readonly, nonatomic) NSArray *recommendedCategories;
@property(readonly, nonatomic) NSArray *topLevelRecommendedChannelTagIDs;
@property(readonly, nonatomic) NSArray *topLevelRecommendedTopicTagIDs;
@property(readonly, nonatomic) NSArray *topLevelCuratedTagIDs;
- (id)initWithContext:(id)arg1 cacheDirectory:(id)arg2;
- (id)init;

@end

