//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCArticleIDFeedDescriptor.h>

@class NSArray;

@interface FCArticlesFeedDescriptor : FCArticleIDFeedDescriptor
{
    NSArray *_articleIDs;
}

@property(readonly, nonatomic) NSArray *articleIDs; // @synthesize articleIDs=_articleIDs;
- (void).cxx_destruct;
- (id)streamOfLatestArticleIDs;
- (id)name;
- (id)initWithContext:(id)arg1 identifier:(id)arg2 articleIDs:(id)arg3;

@end

