//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCArticleIDFeedDescriptor.h>

@class NSString;

@interface FCArticleListFeedDescriptor : FCArticleIDFeedDescriptor
{
    NSString *_articleListID;
    NSString *_feedName;
}

@property(retain, nonatomic) NSString *feedName; // @synthesize feedName=_feedName;
@property(readonly, nonatomic) NSString *articleListID; // @synthesize articleListID=_articleListID;
- (void).cxx_destruct;
- (id)name;
- (id)streamOfLatestArticleIDs;
- (void)fetchArticleIDsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)initWithContext:(id)arg1 identifier:(id)arg2 articleListID:(id)arg3 name:(id)arg4;

@end

