//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;

@interface FCAsyncSerialQueue : NSObject
{
    NSOperationQueue *_serialOperationQueue;
}

@property(retain, nonatomic) NSOperationQueue *serialOperationQueue; // @synthesize serialOperationQueue=_serialOperationQueue;
- (void).cxx_destruct;
- (void)cancelAllBlocks;
- (void)enqueueBlockForMainThread:(CDUnknownBlockType)arg1;
- (void)enqueueWithQualityOfService:(long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)enqueueBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

