//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSURL;

@interface FCBlobFileCacheItem : NSObject
{
    NSURL *_url;
    NSDate *_lastModified;
}

@property(copy, nonatomic) NSDate *lastModified; // @synthesize lastModified=_lastModified;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;

@end

