//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCOperation.h>

@interface FCCKOperation : FCOperation
{
}

@property(readonly, nonatomic) long long queuePriorityForChildCKOperation;
- (_Bool)canRetryWithError:(id)arg1 retryAfter:(double *)arg2;
- (unsigned long long)maxRetries;

@end

