//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCCKDatabase.h>

@interface FCCKDatabase (FCCloudKitConnection)
+ (id)fc_contentDatabaseMiddleware;
+ (id)fc_privateDatabaseMiddlewareWithOptions:(long long)arg1;
+ (id)fc_databaseForContentCloudKitDatabase:(id)arg1;
+ (id)fc_databaseForPrivateCloudKitDatabase:(id)arg1;
@end

