//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSObject-Protocol.h>

@class CKRecord, CKRecordID, CKRecordZone, CKRecordZoneID, FCCKDatabase;

@protocol FCCKDatabaseRecordMiddleware <NSObject>
- (CKRecordZone *)serverRecordZone:(CKRecordZone *)arg1 inDatabase:(FCCKDatabase *)arg2;
- (CKRecordZone *)clientRecordZone:(CKRecordZone *)arg1 inDatabae:(FCCKDatabase *)arg2;
- (CKRecord *)serverRecord:(CKRecord *)arg1 inDatabase:(FCCKDatabase *)arg2;
- (CKRecord *)clientRecord:(CKRecord *)arg1 inDatabase:(FCCKDatabase *)arg2;
- (CKRecordZoneID *)clientRecordZoneID:(CKRecordZoneID *)arg1 inDatabase:(FCCKDatabase *)arg2;
- (CKRecordZoneID *)serverRecordZoneID:(CKRecordZoneID *)arg1 inDatabase:(FCCKDatabase *)arg2;
- (CKRecordID *)clientRecordID:(CKRecordID *)arg1 inDatabase:(FCCKDatabase *)arg2;
- (CKRecordID *)serverRecordID:(CKRecordID *)arg1 inDatabase:(FCCKDatabase *)arg2;
@end

