//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSObject-Protocol.h>

@class CKDatabaseOperation, FCCKDatabase;

@protocol FCCKDatabaseOperationMiddleware <NSObject>
- (void)database:(FCCKDatabase *)arg1 didCancelOperation:(CKDatabaseOperation *)arg2;
- (long long)database:(FCCKDatabase *)arg1 willEnqueueOperation:(CKDatabaseOperation *)arg2;
@end

