//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CKDatabase, NSArray, NSMutableArray, NSString;
@protocol FCCKDatabaseDelegate, OS_dispatch_queue;

@interface FCCKDatabase : NSObject
{
    _Bool _hasBeenRateLimited;
    _Bool _preferAnonymousRequests;
    _Bool _ready;
    id <FCCKDatabaseDelegate> _delegate;
    NSArray *_middleware;
    NSString *_containerIdentifier;
    CKDatabase *_database;
    NSObject<OS_dispatch_queue> *_queue;
    NSArray *_startUpMiddleware;
    NSArray *_operationMiddleware;
    NSArray *_recordMiddleware;
    NSMutableArray *_pendingOperations;
    long long _status;
    CDUnknownBlockType _startUpCompletion;
}

+ (id)testingDatabase;
@property(copy, nonatomic) CDUnknownBlockType startUpCompletion; // @synthesize startUpCompletion=_startUpCompletion;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic, getter=isReady) _Bool ready; // @synthesize ready=_ready;
@property(retain, nonatomic) NSMutableArray *pendingOperations; // @synthesize pendingOperations=_pendingOperations;
@property(retain, nonatomic) NSArray *recordMiddleware; // @synthesize recordMiddleware=_recordMiddleware;
@property(retain, nonatomic) NSArray *operationMiddleware; // @synthesize operationMiddleware=_operationMiddleware;
@property(retain, nonatomic) NSArray *startUpMiddleware; // @synthesize startUpMiddleware=_startUpMiddleware;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) CKDatabase *database; // @synthesize database=_database;
@property _Bool preferAnonymousRequests; // @synthesize preferAnonymousRequests=_preferAnonymousRequests;
@property(readonly, nonatomic) _Bool hasBeenRateLimited; // @synthesize hasBeenRateLimited=_hasBeenRateLimited;
@property(retain, nonatomic) NSString *containerIdentifier; // @synthesize containerIdentifier=_containerIdentifier;
@property(retain, nonatomic) NSArray *middleware; // @synthesize middleware=_middleware;
@property(nonatomic) __weak id <FCCKDatabaseDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_isEnabled;
- (void)_cancelOperation:(id)arg1;
- (id)_mapObjects:(id)arg1 withRecordMiddlewareBlock:(CDUnknownBlockType)arg2;
- (id)_mapZones:(id)arg1 client:(_Bool)arg2;
- (id)_serverZone:(id)arg1;
- (id)_clientZone:(id)arg1;
- (id)_mapRecords:(id)arg1 client:(_Bool)arg2;
- (id)_serverRecord:(id)arg1;
- (id)_clientRecord:(id)arg1;
- (id)_mapRecordZoneIDs:(id)arg1 client:(_Bool)arg2;
- (id)_clientRecordZoneID:(id)arg1;
- (id)_serverRecordZoneID:(id)arg1;
- (id)_mapRecordIDs:(id)arg1 client:(_Bool)arg2;
- (id)_clientRecordID:(id)arg1;
- (id)_serverRecordID:(id)arg1;
- (void)_cacheMiddleware;
- (void)_preflightModifySubscriptionOperation:(id)arg1;
- (void)_preflightFetchSubscriptionOperation:(id)arg1;
- (void)_preflightZoneIDsInModifyZonesOperation:(id)arg1;
- (void)_preflightZonesIDsInFetchZonesOperation:(id)arg1;
- (void)_preflightRecordsInQueryOperation:(id)arg1;
- (void)_preflightRecordsInFetchOperation:(id)arg1;
- (void)_preflightRecordsInChangesOperation:(id)arg1;
- (void)_preflightRecordsInModifyOperation:(id)arg1;
- (_Bool)_preflightOperation:(id)arg1;
- (void)q_cancelPendingOperations;
- (void)q_resumePendingOperations;
- (void)_addOperation:(id)arg1;
- (void)q_finishStartUpWithResult:(long long)arg1;
- (void)q_startUpWithMiddleware:(id)arg1;
- (void)_performStartUpWithCompletion:(CDUnknownBlockType)arg1;
- (void)clearCloudKitCaches;
- (id)serverSubscriptonFromSubscription:(id)arg1;
- (void)operationWasRateLimitedWithError:(id)arg1;
- (id)notificationFromRemoteNotificationDictionary:(id)arg1;
- (void)addOperation:(id)arg1;
- (id)initWithDatabase:(id)arg1 middleware:(id)arg2;
- (id)initWithDatabase:(id)arg1 middleware:(id)arg2 startUp:(_Bool)arg3;

@end

