//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCCKDatabase.h>

@interface FCCKDatabase (Additions)
- (void)deleteSubscriptionWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)saveSubscription:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)fetchAllSubscriptionsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)deleteRecordZoneWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)saveRecordZone:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)fetchRecordZoneWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteRecordWithID:(id)arg1 savePolicy:(long long)arg2 zoneBusyRetryCount:(unsigned long long)arg3 zoneBusyRetryMax:(unsigned long long)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)deleteRecordWithID:(id)arg1 savePolicy:(long long)arg2 retryWhenZoneBusy:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)deleteRecordsWithIDs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteRecordWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)performRecordIDsQuery:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)performQuery:(id)arg1 inZoneWithID:(id)arg2 desiredKeys:(id)arg3 resultsLimit:(unsigned long long)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)performQuery:(id)arg1 inZoneWithID:(id)arg2 desiredKeys:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)performQuery:(id)arg1 desiredKeys:(id)arg2 resultsLimit:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)performQuery:(id)arg1 desiredKeys:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)saveRecords:(id)arg1 savePolicy:(long long)arg2 progressHandler:(CDUnknownBlockType)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)saveRecord:(id)arg1 savePolicy:(long long)arg2 zoneBusyRetryCount:(unsigned long long)arg3 zoneBusyRetryMax:(unsigned long long)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)saveRecords:(id)arg1 progressHandler:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)saveRecord:(id)arg1 savePolicy:(long long)arg2 retryWhenZoneBusy:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)saveRecord:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)fetchRecordsWithIDs:(id)arg1 desiredKeys:(id)arg2 qualityOfService:(long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)fetchRecordsWithIDs:(id)arg1 desiredKeys:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)fetchRecordWithID:(id)arg1 desiredKeys:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)fetchRecordWithID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
@end

