//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/FCCKDatabaseDelegate-Protocol.h>

@class CKContainer, FCCKDatabase, FCCKRecordZone, FCCKRecordZoneManager, NSString;
@protocol FCCloudKitConnectionDelegate;

@interface FCCloudKitConnection : NSObject <FCCKDatabaseDelegate>
{
    _Bool _testing;
    id <FCCloudKitConnectionDelegate> _delegate;
    FCCKDatabase *_contentDatabase;
    FCCKDatabase *_privateDatabase;
    NSString *_cacheDirectory;
    NSString *_privateDataDirectory;
    FCCKRecordZoneManager *_recordZoneManager;
    CKContainer *_contentContainer;
    CKContainer *_privateContainer;
}

+ (id)testingConnection;
@property(retain, nonatomic) CKContainer *privateContainer; // @synthesize privateContainer=_privateContainer;
@property(retain, nonatomic) CKContainer *contentContainer; // @synthesize contentContainer=_contentContainer;
@property(nonatomic) _Bool testing; // @synthesize testing=_testing;
@property(retain, nonatomic) FCCKRecordZoneManager *recordZoneManager; // @synthesize recordZoneManager=_recordZoneManager;
@property(readonly, copy, nonatomic) NSString *privateDataDirectory; // @synthesize privateDataDirectory=_privateDataDirectory;
@property(readonly, copy, nonatomic) NSString *cacheDirectory; // @synthesize cacheDirectory=_cacheDirectory;
@property(retain, nonatomic) FCCKDatabase *privateDatabase; // @synthesize privateDatabase=_privateDatabase;
@property(retain, nonatomic) FCCKDatabase *contentDatabase; // @synthesize contentDatabase=_contentDatabase;
@property(nonatomic) __weak id <FCCloudKitConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clearCloudKitCaches;
- (void)setPreferAnonymousRequests:(_Bool)arg1;
- (void)databaseHasBeenRateLimited:(id)arg1 retryAfter:(double)arg2;
@property(readonly, nonatomic) _Bool hasBeenRateLimited;
- (id)recordZoneWithName:(id)arg1;
@property(readonly, nonatomic) FCCKRecordZone *channelMembershipsRecordZone;
@property(readonly, nonatomic) FCCKRecordZone *userInfoRecordZone;
@property(readonly, nonatomic) FCCKRecordZone *readingHistoryRecordZone;
@property(readonly, nonatomic) FCCKRecordZone *subscriptionsRecordZone;
@property(readonly, nonatomic) FCCKRecordZone *readingListRecordZone;
- (void)dealloc;
- (id)initWithContentDatabase:(id)arg1 privateDatabase:(id)arg2 cacheDirectory:(id)arg3 privateDataDirectory:(id)arg4;
- (id)initWithContentContainerIdentifier:(id)arg1 privateContainerIdentifier:(id)arg2 environment:(long long)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

