//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSObject-Protocol.h>

@class FCCloudKitConnection, NSArray;

@protocol FCCloudKitConnectionDelegate <NSObject>
- (void)cloudKitConnectionPrivateDatabaseHasBeenRateLimited:(FCCloudKitConnection *)arg1;
- (void)cloudKitConnectionContentDatabaseHasBeenRateLimited:(FCCloudKitConnection *)arg1;
- (void)cloudKitConnection:(FCCloudKitConnection *)arg1 didDropRecordZonesWithIDs:(NSArray *)arg2;
@end

