//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSObject-Protocol.h>

@class FCFeedInbox, NSArray;

@protocol FCFeedInboxObserving <NSObject>

@optional
- (void)feedInboxDidChangePersistableState:(FCFeedInbox *)arg1;
- (void)feedInbox:(FCFeedInbox *)arg1 didUpdateHeadlines:(NSArray *)arg2;
- (void)feedInbox:(FCFeedInbox *)arg1 didDeleteHeadlinesWithIDs:(NSArray *)arg2;
@end

