//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMapTable;

@interface FCFeedPersonalizedArticles : NSObject
{
    NSArray *_articlesToShow;
    NSArray *_articlesToHold;
    NSArray *_articlesToDiscard;
    NSMapTable *_articleScores;
    NSMapTable *_featuresScores;
}

@property(retain, nonatomic) NSMapTable *featuresScores; // @synthesize featuresScores=_featuresScores;
@property(retain, nonatomic) NSMapTable *articleScores; // @synthesize articleScores=_articleScores;
@property(retain, nonatomic) NSArray *articlesToDiscard; // @synthesize articlesToDiscard=_articlesToDiscard;
@property(retain, nonatomic) NSArray *articlesToHold; // @synthesize articlesToHold=_articlesToHold;
@property(retain, nonatomic) NSArray *articlesToShow; // @synthesize articlesToShow=_articlesToShow;
- (void).cxx_destruct;

@end

