//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCOperation.h>

@class FCAppConfiguration, FCFeedItemBatch, FCFeedPersonalizingSession, NSArray, NSError, NSOrderedSet, NSSet;
@protocol FCFeedPersonalizing, FCInboxStyleFeed, FCInboxStyleFeedCursor;

@interface FCFeedInboxRefreshOperation : FCOperation
{
    _Bool _caughtUp;
    id <FCInboxStyleFeed> _inboxStyleFeed;
    FCAppConfiguration *_appConfiguration;
    id <FCFeedPersonalizing> _feedPersonalizer;
    NSArray *_currentBatches;
    unsigned long long _desiredCount;
    NSSet *_mutedChannelTagIDs;
    CDUnknownBlockType _refreshCompletionHandler;
    id <FCInboxStyleFeedCursor> _refreshToCursor;
    NSArray *_feedItemsFromCurrentBatches;
    NSSet *_articleIDsFromCurrentBatches;
    FCFeedPersonalizingSession *_personalizationSession;
    unsigned long long _desiredCountForPersonalization;
    NSSet *_deletedArticleIDsInCurrentBatches;
    NSOrderedSet *_unfilteredFeedItems;
    id <FCInboxStyleFeedCursor> _topCursor;
    id <FCInboxStyleFeedCursor> _bottomCursor;
    FCFeedItemBatch *_topBatch;
    NSError *_refreshError;
}

@property(retain, nonatomic) NSError *refreshError; // @synthesize refreshError=_refreshError;
@property(nonatomic) _Bool caughtUp; // @synthesize caughtUp=_caughtUp;
@property(retain, nonatomic) FCFeedItemBatch *topBatch; // @synthesize topBatch=_topBatch;
@property(retain, nonatomic) id <FCInboxStyleFeedCursor> bottomCursor; // @synthesize bottomCursor=_bottomCursor;
@property(retain, nonatomic) id <FCInboxStyleFeedCursor> topCursor; // @synthesize topCursor=_topCursor;
@property(retain, nonatomic) NSOrderedSet *unfilteredFeedItems; // @synthesize unfilteredFeedItems=_unfilteredFeedItems;
@property(retain, nonatomic) NSSet *deletedArticleIDsInCurrentBatches; // @synthesize deletedArticleIDsInCurrentBatches=_deletedArticleIDsInCurrentBatches;
@property(nonatomic) unsigned long long desiredCountForPersonalization; // @synthesize desiredCountForPersonalization=_desiredCountForPersonalization;
@property(retain, nonatomic) FCFeedPersonalizingSession *personalizationSession; // @synthesize personalizationSession=_personalizationSession;
@property(retain, nonatomic) NSSet *articleIDsFromCurrentBatches; // @synthesize articleIDsFromCurrentBatches=_articleIDsFromCurrentBatches;
@property(retain, nonatomic) NSArray *feedItemsFromCurrentBatches; // @synthesize feedItemsFromCurrentBatches=_feedItemsFromCurrentBatches;
@property(retain, nonatomic) id <FCInboxStyleFeedCursor> refreshToCursor; // @synthesize refreshToCursor=_refreshToCursor;
@property(copy, nonatomic) CDUnknownBlockType refreshCompletionHandler; // @synthesize refreshCompletionHandler=_refreshCompletionHandler;
@property(copy, nonatomic) NSSet *mutedChannelTagIDs; // @synthesize mutedChannelTagIDs=_mutedChannelTagIDs;
@property(nonatomic) unsigned long long desiredCount; // @synthesize desiredCount=_desiredCount;
@property(retain, nonatomic) NSArray *currentBatches; // @synthesize currentBatches=_currentBatches;
@property(retain, nonatomic) id <FCFeedPersonalizing> feedPersonalizer; // @synthesize feedPersonalizer=_feedPersonalizer;
@property(retain, nonatomic) FCAppConfiguration *appConfiguration; // @synthesize appConfiguration=_appConfiguration;
@property(retain, nonatomic) id <FCInboxStyleFeed> inboxStyleFeed; // @synthesize inboxStyleFeed=_inboxStyleFeed;
- (void).cxx_destruct;
- (void)_finalizeTopBatch;
- (void)_continueFetchingFeedItemsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)operationWillFinishWithError:(id)arg1;
- (void)performOperation;
- (void)prepareOperation;
- (_Bool)validateOperation;

@end

