//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCFeedManager.h>

@interface FCFeedManager (FCFeedGeneration)
- (id)storeKeyForStateOfFeedInbox:(id)arg1;
- (void)feedInboxDidChangePersistableState:(id)arg1;
- (id)feedInboxForFeedDescriptor:(id)arg1;
- (id)_feedDescriptorWithIdentifier:(id)arg1 forceRecreate:(_Bool)arg2 tag:(id)arg3;
- (id)feedDescriptorWithIdentifier:(id)arg1;
- (id)feedDescriptorForArticleIDs:(id)arg1;
- (id)feedDescriptorForArticlesInSameClusterAsArticleID:(id)arg1;
- (id)feedDescriptorForTag:(id)arg1;
- (id)feedDescriptorForReadingList;
- (id)feedDescriptorForReadingHistory;
- (id)feedDescriptorForForYou;
@end

