//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSObject-Protocol.h>

@class NSArray, NSDate, NSString;

@protocol FCFeedPersonalizingArticle <NSObject>
@property(readonly, nonatomic) _Bool mustShow;
@property(readonly, nonatomic) unsigned long long articleContentType;
@property(readonly, nonatomic) NSString *surfacedBySectionID;
@property(readonly, nonatomic) NSString *surfacedByTopicID;
@property(readonly, nonatomic) NSString *surfacedByChannelID;
@property(readonly, nonatomic) double globalUserFeedback;
@property(readonly, nonatomic) NSArray *topicWeights;
@property(readonly, nonatomic) NSArray *topicIDs;
@property(readonly, nonatomic) NSString *publisherID;
@property(readonly, nonatomic) unsigned long long halfLife;
@property(readonly, nonatomic) NSDate *orderDate;
@property(readonly, nonatomic) NSDate *publishDate;
@property(readonly, nonatomic) NSString *feedID;
@property(readonly, nonatomic) NSString *articleID;
@end

