//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSCopying-Protocol.h>
#import <NewsCore/NSObject-Protocol.h>

@class NSString;

@protocol FCFeedInboxElement <NSObject, NSCopying>
- (NSString *)identifier;
- (long long)feedInboxElementType;
@end

