//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/FCFeedHeadlineSource-Protocol.h>
#import <NewsCore/NSCopying-Protocol.h>

@class FCCloudContext, NSArray, NSString;
@protocol FCFeedTheming, FCTagProviding;

@interface FCFeedDescriptor : NSObject <NSCopying, FCFeedHeadlineSource>
{
    FCCloudContext *_context;
    long long _feedType;
    NSString *_identifier;
}

@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) long long feedType; // @synthesize feedType=_feedType;
@property(readonly, nonatomic) FCCloudContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)fetchHeadlinesForIdentifiers:(id)arg1 downloadAssets:(_Bool)arg2 qualityOfService:(long long)arg3 completion:(CDUnknownBlockType)arg4;
@property(readonly, copy) NSString *description;
- (id)latestHeadlineResults;
- (id)fetchOperationForHeadlinesWithIDs:(id)arg1;
- (id)streamOfLatestHeadlines;
- (id)streamOfHeadlinesWithIDs:(id)arg1 cachedOnly:(_Bool)arg2 maxCachedAge:(double)arg3;
@property(readonly, nonatomic) NSString *iAdSectionID;
@property(readonly, nonatomic) NSString *iAdFeedID;
@property(readonly, nonatomic) NSString *iAdPrimaryAudience;
@property(readonly, nonatomic) long long iAdContentProvider;
@property(readonly, nonatomic) NSArray *iAdCategories;
@property(readonly, nonatomic) NSString *backingTopicID;
@property(readonly, nonatomic) NSString *backingSectionID;
@property(readonly, nonatomic) NSString *backingChannelID;
@property(readonly, nonatomic) id <FCTagProviding> backingTag;
@property(readonly, nonatomic) _Bool isSubscribedTo;
- (void)unsubscribeTo;
- (_Bool)subscribeToWithError:(id *)arg1;
@property(readonly, nonatomic) _Bool isSubscribable;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) _Bool isInboxStyleFeed;
@property(readonly, nonatomic) id <FCFeedTheming> theme;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithContext:(id)arg1 identifier:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

