//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCOperation.h>

@class FCAppConfiguration, FCFeedItemBatch, FCFeedPersonalizingSession, NSArray, NSError, NSOrderedSet, NSSet;
@protocol FCFeedPersonalizing, FCInboxStyleFeed, FCInboxStyleFeedCursor;

@interface FCFeedInboxExtendOperation : FCOperation
{
    _Bool _caughtUp;
    id <FCInboxStyleFeed> _inboxStyleFeed;
    FCAppConfiguration *_appConfiguration;
    id <FCFeedPersonalizing> _feedPersonalizer;
    FCFeedItemBatch *_batchToExtend;
    NSArray *_currentBatches;
    unsigned long long _desiredCount;
    NSSet *_mutedChannelTagIDs;
    CDUnknownBlockType _extendCompletionHandler;
    id <FCInboxStyleFeedCursor> _extendFromCursor;
    id <FCInboxStyleFeedCursor> _extendToCursor;
    NSArray *_feedItemsFromCurrentBatches;
    FCFeedPersonalizingSession *_personalizationSession;
    unsigned long long _desiredCountForPersonalization;
    NSOrderedSet *_unfilteredFeedItems;
    id <FCInboxStyleFeedCursor> _topCursor;
    id <FCInboxStyleFeedCursor> _bottomCursor;
    FCFeedItemBatch *_extensionBatch;
    NSError *_extendError;
}

@property(retain, nonatomic) NSError *extendError; // @synthesize extendError=_extendError;
@property(nonatomic) _Bool caughtUp; // @synthesize caughtUp=_caughtUp;
@property(retain, nonatomic) FCFeedItemBatch *extensionBatch; // @synthesize extensionBatch=_extensionBatch;
@property(retain, nonatomic) id <FCInboxStyleFeedCursor> bottomCursor; // @synthesize bottomCursor=_bottomCursor;
@property(retain, nonatomic) id <FCInboxStyleFeedCursor> topCursor; // @synthesize topCursor=_topCursor;
@property(retain, nonatomic) NSOrderedSet *unfilteredFeedItems; // @synthesize unfilteredFeedItems=_unfilteredFeedItems;
@property(nonatomic) unsigned long long desiredCountForPersonalization; // @synthesize desiredCountForPersonalization=_desiredCountForPersonalization;
@property(retain, nonatomic) FCFeedPersonalizingSession *personalizationSession; // @synthesize personalizationSession=_personalizationSession;
@property(retain, nonatomic) NSArray *feedItemsFromCurrentBatches; // @synthesize feedItemsFromCurrentBatches=_feedItemsFromCurrentBatches;
@property(retain, nonatomic) id <FCInboxStyleFeedCursor> extendToCursor; // @synthesize extendToCursor=_extendToCursor;
@property(retain, nonatomic) id <FCInboxStyleFeedCursor> extendFromCursor; // @synthesize extendFromCursor=_extendFromCursor;
@property(copy, nonatomic) CDUnknownBlockType extendCompletionHandler; // @synthesize extendCompletionHandler=_extendCompletionHandler;
@property(retain, nonatomic) NSSet *mutedChannelTagIDs; // @synthesize mutedChannelTagIDs=_mutedChannelTagIDs;
@property(nonatomic) unsigned long long desiredCount; // @synthesize desiredCount=_desiredCount;
@property(retain, nonatomic) NSArray *currentBatches; // @synthesize currentBatches=_currentBatches;
@property(retain, nonatomic) FCFeedItemBatch *batchToExtend; // @synthesize batchToExtend=_batchToExtend;
@property(retain, nonatomic) id <FCFeedPersonalizing> feedPersonalizer; // @synthesize feedPersonalizer=_feedPersonalizer;
@property(retain, nonatomic) FCAppConfiguration *appConfiguration; // @synthesize appConfiguration=_appConfiguration;
@property(retain, nonatomic) id <FCInboxStyleFeed> inboxStyleFeed; // @synthesize inboxStyleFeed=_inboxStyleFeed;
- (void).cxx_destruct;
- (void)_finalizeExtensionBatch;
- (void)_continueFetchingFeedItemsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)operationWillFinishWithError:(id)arg1;
- (void)performOperation;
- (void)prepareOperation;
- (_Bool)validateOperation;

@end

