//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOrderedSet;
@protocol FCInboxStyleFeedCursor;

@interface FCFeedItemBatch : NSObject
{
    NSOrderedSet *_feedItems;
    id <FCInboxStyleFeedCursor> _topCursor;
    id <FCInboxStyleFeedCursor> _bottomCursor;
}

+ (id)articleIDsFromBatches:(id)arg1;
+ (id)feedItemsFromBatches:(id)arg1;
+ (id)batchByPrependingBatch:(id)arg1 toBatch:(id)arg2;
+ (id)batchByAppendingBatch:(id)arg1 toBatch:(id)arg2;
+ (id)emptyBatch;
@property(readonly, copy, nonatomic) id <FCInboxStyleFeedCursor> bottomCursor; // @synthesize bottomCursor=_bottomCursor;
@property(readonly, copy, nonatomic) id <FCInboxStyleFeedCursor> topCursor; // @synthesize topCursor=_topCursor;
@property(readonly, copy, nonatomic) NSOrderedSet *feedItems; // @synthesize feedItems=_feedItems;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSOrderedSet *articleIDs;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty;
- (id)initWithFeedItems:(id)arg1 topCursor:(id)arg2 bottomCursor:(id)arg3;
- (id)init;

@end

