//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCMultiTagFeedDescriptor.h>

@interface FCForYouFeedDescriptor : FCMultiTagFeedDescriptor
{
}

+ (void)initialize;
- (void)customizeBottomCursor:(id)arg1 forQueryResult:(id)arg2 feedContext:(id)arg3 fromCursor:(id)arg4 dateRange:(id)arg5 personalizer:(id)arg6;
- (void)customizeFeedRequests:(id)arg1 feedContext:(id)arg2 fromCursor:(id)arg3 dateRange:(id)arg4 minResultsLimit:(unsigned long long)arg5 personalizer:(id)arg6 resultsLimit:(unsigned long long *)arg7 queryType:(long long *)arg8;
- (long long)inboxFilterOptions;
- (long long)inboxSortMethod;
- (_Bool)supportsTopStories;
- (unsigned long long)preferredFeedItemBatchSize;
- (void)fetchPinnedArticleIDsWithQualityOfService:(long long)arg1 networkPriority:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_filterTagsForQuerying:(id)arg1;
- (void)fetchCurrentFeedContextWithQualityOfService:(long long)arg1 networkPriority:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_buildForYouFromTags:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)iAdFeedID;
- (id)name;

@end

