//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/NSCopying-Protocol.h>

@class FCCKRecordZone;

@interface FCHandlePushNotificationResult : NSObject <NSCopying>
{
    _Bool _handled;
    FCCKRecordZone *_recordZone;
}

@property(retain, nonatomic) FCCKRecordZone *recordZone; // @synthesize recordZone=_recordZone;
@property(nonatomic, getter=wasHandled) _Bool handled; // @synthesize handled=_handled;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

