//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSObject-Protocol.h>

@class FCFeedPersonalizingSession;
@protocol FCFeedPersonalizing, FCInboxStyleFeedCursor;

@protocol FCInboxStyleFeed <NSObject>
- (FCFeedPersonalizingSession *)personalizationSessionFromCursor:(id <FCInboxStyleFeedCursor>)arg1 toCursor:(id <FCInboxStyleFeedCursor>)arg2;
- (long long)inboxFilterOptions;
- (long long)inboxSortMethod;
- (id <FCInboxStyleFeedCursor>)cursorByMergingBottomCursor:(id <FCInboxStyleFeedCursor>)arg1 withBottomCursor:(id <FCInboxStyleFeedCursor>)arg2;
- (id <FCInboxStyleFeedCursor>)cursorByMergingTopCursor:(id <FCInboxStyleFeedCursor>)arg1 withTopCursor:(id <FCInboxStyleFeedCursor>)arg2;
- (void)fetchBatchOfFeedItemsFromCursor:(id <FCInboxStyleFeedCursor>)arg1 toCursor:(id <FCInboxStyleFeedCursor>)arg2 minCount:(unsigned long long)arg3 articleTestBlock:(_Bool (^)(NSString *))arg4 personalizer:(id <FCFeedPersonalizing>)arg5 qualityOfService:(long long)arg6 networkPriority:(long long)arg7 completion:(void (^)(FCFeedItemBatch *, _Bool, NSError *))arg8;
@end

