//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSCoding-Protocol.h>
#import <NewsCore/NSCopying-Protocol.h>
#import <NewsCore/NSObject-Protocol.h>

@class FCFeedPersonalizingSessionDeliveredArticleCount, NSArray;

@protocol FCInboxStyleFeedCursor <NSObject, NSCoding, NSCopying>
@property(copy, nonatomic) FCFeedPersonalizingSessionDeliveredArticleCount *articleCount;
@property(copy, nonatomic) NSArray *surplusFeedItems;
@property(readonly, nonatomic, getter=isBottomOfFeed) _Bool bottomOfFeed;
@end

