//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface FCInternationalization : NSObject
{
    _Bool _testing;
    NSArray *_allowedInternationalizationKeys;
    NSString *_overrideStorefrontID;
    NSArray *_overrideLanguageCodes;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSArray *overrideLanguageCodes; // @synthesize overrideLanguageCodes=_overrideLanguageCodes;
@property(copy, nonatomic) NSString *overrideStorefrontID; // @synthesize overrideStorefrontID=_overrideStorefrontID;
@property(nonatomic) _Bool testing; // @synthesize testing=_testing;
- (void).cxx_destruct;
- (void)t_stopOverridingLanguageCodes;
- (void)t_startOverridingLanguageCodes:(id)arg1;
- (void)t_stopOverridingStorefrontID;
- (void)t_startOverridingStorefrontID:(id)arg1;
- (id)_generateAllowedInternationalizationKeys;
@property(readonly, nonatomic) NSArray *allowedInternationalizationKeys; // @synthesize allowedInternationalizationKeys=_allowedInternationalizationKeys;
- (id)init;

@end

