//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCModifyPersonalizationOperation.h>

@interface FCModifyPersonalizationOperation (FCMergeUtility)
+ (void)pruneAggregates:(id)arg1;
+ (void)applyDeltas:(id)arg1 toProfile:(id)arg2 treatment:(id)arg3 prune:(_Bool)arg4;
+ (void)applyChangeGroups:(id)arg1 toProfile:(id)arg2 treatment:(id)arg3 prune:(_Bool)arg4;
+ (id)personalizationProfileFromRecord:(id)arg1;
@end

