//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCModifyRecordsCommand.h>

@interface FCModifyUserInfoCommand : FCModifyRecordsCommand
{
}

+ (id)desiredKeys;
- (_Bool)mergeLocalRecord:(id)arg1 withRemoteRecord:(id)arg2;
- (id)recordZoneName;
- (id)initWithFirstLaunchVersion:(id)arg1 feldsparID:(id)arg2 dateLastOpened:(id)arg3 displayedTopStoriesIntroduction:(_Bool)arg4;

@end

