//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface FCMultiTagFeedQueryResult : NSObject
{
    NSArray *_tagFeedResponses;
    NSArray *_allFeedItems;
}

@property(copy, nonatomic) NSArray *allFeedItems; // @synthesize allFeedItems=_allFeedItems;
@property(copy, nonatomic) NSArray *tagFeedResponses; // @synthesize tagFeedResponses=_tagFeedResponses;
- (void).cxx_destruct;
- (_Bool)fulfilledAllRequests:(id)arg1;
- (id)bottomCursorsForRequests:(id)arg1;
- (id)topCursorsForRequests:(id)arg1;
- (id)tagFeedResponsesForRequests:(id)arg1;
- (id)feedItemsForRequests:(id)arg1;

@end

