//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/FCInboxStyleFeedCursor-Protocol.h>

@class FCFeedPersonalizingSessionDeliveredArticleCount, FCMultiTagFeedContext, NSArray, NSDictionary, NSString;

@interface FCMultiTagFeedCursor : NSObject <FCInboxStyleFeedCursor>
{
    NSDictionary *_cursorsByTagID;
    NSDictionary *_cursorsByFeedID;
    _Bool _needsLowerVolume;
    NSArray *_surplusFeedItems;
    FCFeedPersonalizingSessionDeliveredArticleCount *_articleCount;
    FCMultiTagFeedContext *_context;
    long long _lastQueryType;
    NSArray *_cursors;
}

+ (id)dateRangeFromCursor:(id)arg1 toCursor:(id)arg2;
@property(nonatomic) _Bool needsLowerVolume; // @synthesize needsLowerVolume=_needsLowerVolume;
@property(retain, nonatomic) NSArray *cursors; // @synthesize cursors=_cursors;
@property(nonatomic) long long lastQueryType; // @synthesize lastQueryType=_lastQueryType;
@property(retain, nonatomic) FCMultiTagFeedContext *context; // @synthesize context=_context;
@property(copy, nonatomic) FCFeedPersonalizingSessionDeliveredArticleCount *articleCount; // @synthesize articleCount=_articleCount;
@property(copy, nonatomic) NSArray *surplusFeedItems; // @synthesize surplusFeedItems=_surplusFeedItems;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)cursorsByFeedID;
- (id)cursorsByTagID;
- (_Bool)hasCursorForTagID:(id)arg1;
- (id)bottomCursorForTagID:(id)arg1 feedID:(id)arg2;
- (id)topCursorForTagID:(id)arg1 feedID:(id)arg2;
- (id)copyByMergingWithBottomCursor:(id)arg1;
- (id)copyByMergingWithTopCursor:(id)arg1;
@property(readonly, nonatomic, getter=isBottomOfFeed) _Bool bottomOfFeed;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

