//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSURL;

@interface FCNetworkEvent : NSObject
{
    long long _type;
    NSURL *_url;
    NSString *_requestUUID;
    double _startTime;
    NSDictionary *_w3cNavigationTiming;
    unsigned long long _responseSize;
    unsigned long long _httpStatusCode;
    NSDictionary *_httpResponseHeaders;
    unsigned long long _errorCode;
}

@property(nonatomic) unsigned long long errorCode; // @synthesize errorCode=_errorCode;
@property(retain, nonatomic) NSDictionary *httpResponseHeaders; // @synthesize httpResponseHeaders=_httpResponseHeaders;
@property(nonatomic) unsigned long long httpStatusCode; // @synthesize httpStatusCode=_httpStatusCode;
@property(nonatomic) unsigned long long responseSize; // @synthesize responseSize=_responseSize;
@property(retain, nonatomic) NSDictionary *w3cNavigationTiming; // @synthesize w3cNavigationTiming=_w3cNavigationTiming;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSString *requestUUID; // @synthesize requestUUID=_requestUUID;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
@property(readonly, nonatomic) double responseDuration;
@property(readonly, nonatomic) double requestDuration;
@property(readonly, nonatomic) double connectDuration;
@property(readonly, nonatomic) double dnsDuration;
@property(readonly, nonatomic) double fetchStartTime;
@property(readonly, nonatomic) double totalDuration;

@end

