//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;
@protocol FCNonDestructivePrivateDataActionProvider;

@interface FCNonDestructivePrivateDataMigrationHandler : NSObject
{
    id <FCNonDestructivePrivateDataActionProvider> _privateDataActionProvider;
    NSArray *_privateZoneControllers;
}

@property(copy, nonatomic) NSArray *privateZoneControllers; // @synthesize privateZoneControllers=_privateZoneControllers;
@property(retain, nonatomic) id <FCNonDestructivePrivateDataActionProvider> privateDataActionProvider; // @synthesize privateDataActionProvider=_privateDataActionProvider;
- (void).cxx_destruct;
- (void)handleMigration;
- (id)initWithPrivateDataActionProvider:(id)arg1 privateZoneControllers:(id)arg2;
- (id)init;

@end

