//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

#import <NewsCore/FCOperationPrioritizing-Protocol.h>

@class FCMutexLock, NSMutableArray, NSString;

@interface FCOperation : NSOperation <FCOperationPrioritizing>
{
    _Bool _executing;
    _Bool _finished;
    _Bool _childOperationsCancelled;
    _Bool _childOperationsFinished;
    long long _networkPriority;
    NSString *_operationID;
    NSMutableArray *_childOperations;
    FCMutexLock *_childOperationsLock;
    double _operationStartTime;
    double _operationEndTime;
    unsigned long long _retryCount;
}

@property(nonatomic) unsigned long long retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) double operationEndTime; // @synthesize operationEndTime=_operationEndTime;
@property(nonatomic) double operationStartTime; // @synthesize operationStartTime=_operationStartTime;
@property(retain, nonatomic) FCMutexLock *childOperationsLock; // @synthesize childOperationsLock=_childOperationsLock;
@property(nonatomic) _Bool childOperationsFinished; // @synthesize childOperationsFinished=_childOperationsFinished;
@property(nonatomic) _Bool childOperationsCancelled; // @synthesize childOperationsCancelled=_childOperationsCancelled;
@property(retain, nonatomic) NSMutableArray *childOperations; // @synthesize childOperations=_childOperations;
@property(readonly, copy, nonatomic) NSString *operationID; // @synthesize operationID=_operationID;
@property(nonatomic) long long networkPriority; // @synthesize networkPriority=_networkPriority;
- (void).cxx_destruct;
- (void)_finishOperationWithError:(id)arg1;
- (void)resetForRetry;
- (_Bool)canRetryWithError:(id)arg1 retryAfter:(double *)arg2;
- (unsigned long long)maxRetries;
- (unsigned long long)propertiesInheritedByChildOperations;
- (void)_associateChildOperation:(id)arg1;
- (void)associateChildOperations:(id)arg1;
- (void)associateChildOperation:(id)arg1;
- (void)operationDidFinishWithError:(id)arg1;
- (void)operationWillFinishWithError:(id)arg1;
- (void)finishedPerformingOperationWithError:(id)arg1;
- (void)performOperation;
- (void)start;
- (void)prepareOperation;
- (_Bool)validateOperation;
- (void)setQualityOfService:(long long)arg1;
- (void)cancel;
- (_Bool)isAsynchronous;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

