//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCPrivateZoneController.h>

#import <NewsCore/FCAppConfigurationObserving-Protocol.h>
#import <NewsCore/FCOperationThrottlerDelegate-Protocol.h>

@class CKRecord, FCPersonalizationTreatment, NSMutableArray, NSMutableDictionary, NSObject, NSString;
@protocol FCOperationThrottler, OS_dispatch_queue;

@interface FCPersonalizationData : FCPrivateZoneController <FCOperationThrottlerDelegate, FCAppConfigurationObserving>
{
    _Bool _attemptingUpload;
    NSMutableDictionary *_aggregates;
    NSMutableDictionary *_openChangeGroupDeltas;
    NSMutableArray *_closedChangeGroups;
    CKRecord *_remoteRecord;
    NSObject<OS_dispatch_queue> *_readWriteQueue;
    FCPersonalizationTreatment *_treatment;
    id <FCOperationThrottler> _saveThrottler;
}

+ (id)localStoreMigrator;
+ (id)desiredKeys;
+ (id)commandsToMergeLocalDataToCloud:(id)arg1;
+ (long long)commandQueueUrgency;
+ (id)commandStoreFileName;
+ (unsigned long long)localStoreVersion;
+ (id)localStoreFilename;
+ (id)recordIDsToSync;
+ (_Bool)requiresHighPriorityFirstSync;
+ (_Bool)requiresBatchedSync;
+ (_Bool)requiresPushNotificationSupport;
+ (void)initialize;
@property _Bool attemptingUpload; // @synthesize attemptingUpload=_attemptingUpload;
@property(retain, nonatomic) id <FCOperationThrottler> saveThrottler; // @synthesize saveThrottler=_saveThrottler;
@property(retain) FCPersonalizationTreatment *treatment; // @synthesize treatment=_treatment;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *readWriteQueue; // @synthesize readWriteQueue=_readWriteQueue;
@property(retain, nonatomic) CKRecord *remoteRecord; // @synthesize remoteRecord=_remoteRecord;
@property(retain, nonatomic) NSMutableArray *closedChangeGroups; // @synthesize closedChangeGroups=_closedChangeGroups;
@property(retain, nonatomic) NSMutableDictionary *openChangeGroupDeltas; // @synthesize openChangeGroupDeltas=_openChangeGroupDeltas;
@property(retain, nonatomic) NSMutableDictionary *aggregates; // @synthesize aggregates=_aggregates;
- (void).cxx_destruct;
- (void)operationThrottler:(id)arg1 performAsyncOperationWithCompletion:(CDUnknownBlockType)arg2;
- (void)appConfigurationDidChange:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
- (void)_closeOpenChangeGroup;
- (void)_writeToLocalStoreWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_updateWithRemoteRecord:(id)arg1 profile:(id)arg2;
- (id)_instanceIdentifier;
- (void)handleSyncWithChangedRecords:(id)arg1 deletedRecordIDs:(id)arg2;
- (void)loadLocalCachesFromStore;
- (void)syncWithCompletion:(CDUnknownBlockType)arg1;
- (id)d_allGlobalAggregates;
- (void)clearPersonalizationData;
- (id)modifyLocalAggregatesForFeatureKeys:(id)arg1 withAction:(unsigned long long)arg2 actionCount:(unsigned long long)arg3 defaultClicks:(double)arg4 defaultImpressions:(double)arg5;
- (id)featureKeysWithNoAggregates:(id)arg1;
- (id)aggregateForFeatureKey:(id)arg1;
- (id)aggregatesForFeatureKeys:(id)arg1;
@property(readonly, nonatomic) FCPersonalizationTreatment *personalizationTreatment;
- (id)initWithContext:(id)arg1 recordZone:(id)arg2 storeDirectory:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

