//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSCopying-Protocol.h>
#import <NewsCore/NSObject-Protocol.h>

@class NSDate, NSString;

@protocol FCReadingHistoryItem <NSObject, NSCopying>
@property(nonatomic) unsigned long long articleLikingStatus;
@property(nonatomic) _Bool hasArticleBeenConsumed;
@property(nonatomic) _Bool hasArticleBeenMarkedOffensive;
@property(nonatomic) _Bool hasArticleBeenSeen;
@property(nonatomic) _Bool hasArticleBeenRead;
@property(copy, nonatomic) NSDate *lastVisitedAt;
@property(copy, nonatomic) NSString *articleID;
@property(readonly, copy, nonatomic) NSString *identifier;
@end

