//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/FCSubscriptionListObserving-Protocol.h>

@class FCSubscriptionList, FCTagController, FCThreadSafeMutableDictionary, NSHashTable, NSString;

@interface FCSubscriptionController : NSObject <FCSubscriptionListObserving>
{
    FCSubscriptionList *_subscriptionList;
    FCTagController *_tagController;
    FCThreadSafeMutableDictionary *_subscribedTagsByTagID;
    NSHashTable *_observers;
}

@property(copy, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) FCThreadSafeMutableDictionary *subscribedTagsByTagID; // @synthesize subscribedTagsByTagID=_subscribedTagsByTagID;
@property(retain, nonatomic) FCTagController *tagController; // @synthesize tagController=_tagController;
@property(retain, nonatomic) FCSubscriptionList *subscriptionList; // @synthesize subscriptionList=_subscriptionList;
- (void).cxx_destruct;
- (void)_handlePendingSubscriptionsAdded:(id)arg1 pendingSubscriptionsChanged:(id)arg2 pendingSubscriptionsRemoved:(id)arg3;
- (void)_handleTagSubscriptionsAdded:(id)arg1 tagSubscriptionsRemoved:(id)arg2;
- (void)_notifyOfTagsAdded:(id)arg1 tagsChanged:(id)arg2 tagsRemoved:(id)arg3;
- (void)_fetchTagsForIDs:(id)arg1 maxCachedAge:(double)arg2 qualityOfService:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_integrateTags:(id)arg1;
- (void)_fetchMissingTagsWithCompletion:(CDUnknownBlockType)arg1;
- (void)subscriptionList:(id)arg1 didAddSubscriptions:(id)arg2 changeSubscriptions:(id)arg3 removeSubscriptions:(id)arg4;
- (void)fetchQueryableSubscribedTagsWithCallbackQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)modifyPendingSubscription:(id)arg1;
- (void)removePendingSubscription:(id)arg1;
- (void)addPendingSubscription:(id)arg1;
- (id)pendingSubscriptionForPollingURL:(id)arg1;
- (id)pendingSubscriptions;
- (void)refreshSubscriptionTags;
- (void)removeSubscriptionToTag:(id)arg1;
- (_Bool)addSubscriptionToTag:(id)arg1 error:(id *)arg2;
- (id)subscriptionForTag:(id)arg1;
- (_Bool)hasSubscriptionToTag:(id)arg1;
- (_Bool)canAddSubscription;
- (id)mutedSubscribedTagIDs;
- (id)subscribedTagIDs;
- (id)subscribedTags;
- (id)subscriptions;
- (id)subscribedTagForTagID:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)initWithSubscriptionList:(id)arg1 tagController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

