//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/FCTagsFetchOperationDelegate-Protocol.h>

@class FCCloudKitConnection, FCTagRecordSource, FCTagsSearchOperation, NSCache, NSString;

@interface FCTagController : NSObject <FCTagsFetchOperationDelegate>
{
    FCCloudKitConnection *_connection;
    FCTagRecordSource *_tagRecordSource;
    NSCache *_fastCache;
    FCTagsSearchOperation *_topicSearchOperation;
    FCTagsSearchOperation *_channelSearchOperation;
}

+ (_Bool)isTagAllowedInCurrentStorefront:(id)arg1;
+ (_Bool)isTagAllowed:(id)arg1;
@property(retain, nonatomic) FCTagsSearchOperation *channelSearchOperation; // @synthesize channelSearchOperation=_channelSearchOperation;
@property(retain, nonatomic) FCTagsSearchOperation *topicSearchOperation; // @synthesize topicSearchOperation=_topicSearchOperation;
@property(retain, nonatomic) NSCache *fastCache; // @synthesize fastCache=_fastCache;
@property(retain, nonatomic) FCTagRecordSource *tagRecordSource; // @synthesize tagRecordSource=_tagRecordSource;
@property(retain, nonatomic) FCCloudKitConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)tagsFetchOperation:(id)arg1 didFetchTagsByID:(id)arg2;
- (void)fetchChannelsForSearchString:(id)arg1 batchSize:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchTopicsForSearchString:(id)arg1 batchSize:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (long long)_inferNetworkPriorityForQualityOfService:(long long)arg1;
- (void)_fetchTagsForTagIDs:(id)arg1 qualityOfService:(long long)arg2 callbackQueue:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)_fetchTagForTagID:(id)arg1 qualityOfService:(long long)arg2 callbackQueue:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)_cachedTagsForTagIDs:(id)arg1;
- (id)_cachedTagForTagID:(id)arg1;
- (id)tagsForTagIDs:(id)arg1;
- (id)tagsForTagIDs:(id)arg1 predicate:(CDUnknownBlockType)arg2;
- (id)tagsForTagIDs:(id)arg1 maximumCachedAge:(double)arg2 predicate:(CDUnknownBlockType)arg3;
- (void)fetchTagForTagID:(id)arg1 qualityOfService:(long long)arg2 callbackQueue:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)fetchTagsForTagIDs:(id)arg1 callbackQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)fetchTagsForTagIDs:(id)arg1 qualityOfService:(long long)arg2 callbackQueue:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)fetchTagsForTagIDs:(id)arg1 maximumCachedAge:(double)arg2 qualityOfService:(long long)arg3 callbackQueue:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)fetchOperationForTagsWithIDs:(id)arg1;
- (id)cachedTagsForIDs:(id)arg1;
- (id)cachedTagForID:(id)arg1;
- (id)initWithConnection:(id)arg1 tagRecordSource:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

