//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCOperation.h>

@class FCCloudKitConnection, FCStreamingResults, FCTagRecordSource, NSError, NSString;

@interface FCTagsSearchOperation : FCOperation
{
    CDUnknownBlockType _searchResultsBlock;
    FCTagRecordSource *_tagRecordSource;
    FCCloudKitConnection *_connection;
    NSString *_searchString;
    unsigned long long _tagType;
    unsigned long long _batchSize;
    FCStreamingResults *_searchResults;
    NSError *_searchError;
}

@property(retain, nonatomic) NSError *searchError; // @synthesize searchError=_searchError;
@property(retain, nonatomic) FCStreamingResults *searchResults; // @synthesize searchResults=_searchResults;
@property(nonatomic) unsigned long long batchSize; // @synthesize batchSize=_batchSize;
@property(nonatomic) unsigned long long tagType; // @synthesize tagType=_tagType;
@property(copy, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(retain, nonatomic) FCCloudKitConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) FCTagRecordSource *tagRecordSource; // @synthesize tagRecordSource=_tagRecordSource;
@property(copy) CDUnknownBlockType searchResultsBlock; // @synthesize searchResultsBlock=_searchResultsBlock;
- (void).cxx_destruct;
- (id)_establishStreamOfTags;
- (void)_performSearchQuery:(CDUnknownBlockType)arg1;
- (void)operationWillFinishWithError:(id)arg1;
- (void)performOperation;
- (_Bool)validateOperation;
- (id)initWithTagRecordSource:(id)arg1 connection:(id)arg2 searchString:(id)arg3 tagType:(unsigned long long)arg4 batchSize:(unsigned long long)arg5;

@end

