//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FCTagFeedCursor, NSString;

@interface FCTagFeedRequest : NSObject
{
    _Bool _isTopStoriesFeed;
    _Bool _isFirstQuery;
    _Bool _isHiddenFeed;
    NSString *_tagID;
    NSString *_feedID;
    FCTagFeedCursor *_fromCursor;
    FCTagFeedCursor *_toCursor;
    unsigned long long _minFeedItems;
    unsigned long long _maxFeedItems;
    NSString *_sectionID;
    NSString *_channelID;
    NSString *_topicID;
}

@property(nonatomic) _Bool isHiddenFeed; // @synthesize isHiddenFeed=_isHiddenFeed;
@property(nonatomic) _Bool isFirstQuery; // @synthesize isFirstQuery=_isFirstQuery;
@property(nonatomic) _Bool isTopStoriesFeed; // @synthesize isTopStoriesFeed=_isTopStoriesFeed;
@property(copy, nonatomic) NSString *topicID; // @synthesize topicID=_topicID;
@property(copy, nonatomic) NSString *channelID; // @synthesize channelID=_channelID;
@property(copy, nonatomic) NSString *sectionID; // @synthesize sectionID=_sectionID;
@property(nonatomic) unsigned long long maxFeedItems; // @synthesize maxFeedItems=_maxFeedItems;
@property(nonatomic) unsigned long long minFeedItems; // @synthesize minFeedItems=_minFeedItems;
@property(retain, nonatomic) FCTagFeedCursor *toCursor; // @synthesize toCursor=_toCursor;
@property(retain, nonatomic) FCTagFeedCursor *fromCursor; // @synthesize fromCursor=_fromCursor;
@property(copy, nonatomic) NSString *feedID; // @synthesize feedID=_feedID;
@property(copy, nonatomic) NSString *tagID; // @synthesize tagID=_tagID;
- (void).cxx_destruct;
- (id)init;

@end

