//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface FCTagSettingsEntry : NSObject
{
    NSString *_identifier;
    NSString *_tagID;
    NSNumber *_fontMultiplier;
}

@property(readonly, copy, nonatomic) NSNumber *fontMultiplier; // @synthesize fontMultiplier=_fontMultiplier;
@property(readonly, copy, nonatomic) NSString *tagID; // @synthesize tagID=_tagID;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)initWithEntryID:(id)arg1 tagID:(id)arg2 fontMultiplier:(id)arg3;

@end

