//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/NSCoding-Protocol.h>

@class NSData, NSDate, NSNumber, NSString;

@interface FCTagFeedCursor : NSObject <NSCoding>
{
    _Bool _atEnd;
    NSString *_tagID;
    NSString *_feedID;
    NSDate *_date;
    NSData *_cursor;
    NSNumber *_order;
}

@property(nonatomic) _Bool atEnd; // @synthesize atEnd=_atEnd;
@property(copy, nonatomic) NSNumber *order; // @synthesize order=_order;
@property(copy, nonatomic) NSData *cursor; // @synthesize cursor=_cursor;
@property(copy, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *feedID; // @synthesize feedID=_feedID;
@property(copy, nonatomic) NSString *tagID; // @synthesize tagID=_tagID;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

