//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/FCChannelProviding-Protocol.h>
#import <NewsCore/FCFeedTheming-Protocol.h>
#import <NewsCore/FCSectionProviding-Protocol.h>
#import <NewsCore/FCTagProviding-Protocol.h>
#import <NewsCore/FCTopicProviding-Protocol.h>

@class FCAssetHandle, FCHeadlineTemplate, FCInterestToken, FCTagBanner, FCTextInfo, NSArray, NSString, NTPBFeedConfiguration, NTPBTagRecord, UIColor;
@protocol FCChannelProviding, FCFeedTheming, FCSectionProviding, FCTopicProviding;

@interface FCTag : NSObject <FCTagProviding, FCChannelProviding, FCSectionProviding, FCTopicProviding, FCFeedTheming>
{
    _Bool _isPublic;
    _Bool _isDeprecated;
    _Bool _isExplicitContent;
    NSString *_identifier;
    NSString *_versionKey;
    NSString *_name;
    unsigned long long _tagType;
    long long _contentProvider;
    NSString *_primaryAudience;
    NSString *_replacementID;
    NSArray *_relatedTopicIDs;
    NSArray *_relatedChannelIDs;
    NSArray *_relatedTopicIDsForOnboarding;
    NSArray *_relatedChannelIDsForOnboarding;
    NSArray *_iAdCategories;
    NSArray *_blockedStorefrontIDs;
    NSArray *_allowedStorefrontIDs;
    NSArray *_pinnedArticleIDs;
    long long _score;
    NSString *_minimumNewsVersion;
    NSString *_backgroundColorHexString;
    NSString *_foregroundColorHexString;
    FCAssetHandle *_nameImageAssetHandle;
    FCAssetHandle *_nameImageForDarkBackgroundAssetHandle;
    FCAssetHandle *_nameImageMaskAssetHandle;
    FCAssetHandle *_logoImageAssetHandle;
    FCAssetHandle *_coverImageAssetHandle;
    FCTextInfo *_headlineTitleTextInfo;
    FCTextInfo *_headlineExcerptTextInfo;
    FCTextInfo *_headlineBylineTextInfo;
    NSString *_parentID;
    NSArray *_sectionIDs;
    NSString *_defaultSectionID;
    FCHeadlineTemplate *_defaultHeadlineTemplate;
    FCTagBanner *_bannerImageForWhiteBackground;
    FCTagBanner *_bannerImageForThemeBackground;
    FCTagBanner *_bannerImageForMask;
    NTPBTagRecord *_tagRecord;
    FCInterestToken *_tagRecordInterestToken;
    NTPBFeedConfiguration *_feedConfiguration;
    NSString *_pptFeedIDOverride;
    struct CGSize _nameImageSize;
    struct CGSize _nameImageForDarkBackgroundSize;
    struct CGSize _nameImageMaskSize;
    struct UIEdgeInsets _nameImageInsets;
    struct UIEdgeInsets _nameImageForDarkBackgroundInsets;
    struct UIEdgeInsets _nameImageMaskInsets;
}

+ (id)fc_tagPropertyFromLocales:(id)arg1 selector:(SEL)arg2;
@property(copy, nonatomic) NSString *pptFeedIDOverride; // @synthesize pptFeedIDOverride=_pptFeedIDOverride;
@property(copy, nonatomic) NTPBFeedConfiguration *feedConfiguration; // @synthesize feedConfiguration=_feedConfiguration;
@property(readonly, nonatomic) FCInterestToken *tagRecordInterestToken; // @synthesize tagRecordInterestToken=_tagRecordInterestToken;
@property(readonly, nonatomic) NTPBTagRecord *tagRecord; // @synthesize tagRecord=_tagRecord;
@property(readonly, nonatomic) FCHeadlineTemplate *defaultHeadlineTemplate; // @synthesize defaultHeadlineTemplate=_defaultHeadlineTemplate;
@property(readonly, copy, nonatomic) NSString *defaultSectionID; // @synthesize defaultSectionID=_defaultSectionID;
@property(readonly, copy, nonatomic) NSArray *sectionIDs; // @synthesize sectionIDs=_sectionIDs;
@property(readonly, copy, nonatomic) NSString *parentID; // @synthesize parentID=_parentID;
@property(readonly, copy, nonatomic) FCTextInfo *headlineBylineTextInfo; // @synthesize headlineBylineTextInfo=_headlineBylineTextInfo;
@property(readonly, copy, nonatomic) FCTextInfo *headlineExcerptTextInfo; // @synthesize headlineExcerptTextInfo=_headlineExcerptTextInfo;
@property(readonly, copy, nonatomic) FCTextInfo *headlineTitleTextInfo; // @synthesize headlineTitleTextInfo=_headlineTitleTextInfo;
@property(readonly, nonatomic) FCAssetHandle *coverImageAssetHandle; // @synthesize coverImageAssetHandle=_coverImageAssetHandle;
@property(readonly, nonatomic) FCAssetHandle *logoImageAssetHandle; // @synthesize logoImageAssetHandle=_logoImageAssetHandle;
@property(readonly, nonatomic) struct UIEdgeInsets nameImageMaskInsets; // @synthesize nameImageMaskInsets=_nameImageMaskInsets;
@property(readonly, nonatomic) struct CGSize nameImageMaskSize; // @synthesize nameImageMaskSize=_nameImageMaskSize;
@property(readonly, nonatomic) FCAssetHandle *nameImageMaskAssetHandle; // @synthesize nameImageMaskAssetHandle=_nameImageMaskAssetHandle;
@property(readonly, nonatomic) struct UIEdgeInsets nameImageForDarkBackgroundInsets; // @synthesize nameImageForDarkBackgroundInsets=_nameImageForDarkBackgroundInsets;
@property(readonly, nonatomic) struct CGSize nameImageForDarkBackgroundSize; // @synthesize nameImageForDarkBackgroundSize=_nameImageForDarkBackgroundSize;
@property(readonly, nonatomic) FCAssetHandle *nameImageForDarkBackgroundAssetHandle; // @synthesize nameImageForDarkBackgroundAssetHandle=_nameImageForDarkBackgroundAssetHandle;
@property(readonly, nonatomic) struct UIEdgeInsets nameImageInsets; // @synthesize nameImageInsets=_nameImageInsets;
@property(readonly, nonatomic) struct CGSize nameImageSize; // @synthesize nameImageSize=_nameImageSize;
@property(readonly, nonatomic) FCAssetHandle *nameImageAssetHandle; // @synthesize nameImageAssetHandle=_nameImageAssetHandle;
@property(readonly, copy, nonatomic) NSString *foregroundColorHexString; // @synthesize foregroundColorHexString=_foregroundColorHexString;
@property(readonly, copy, nonatomic) NSString *backgroundColorHexString; // @synthesize backgroundColorHexString=_backgroundColorHexString;
@property(readonly, copy, nonatomic) NSString *minimumNewsVersion; // @synthesize minimumNewsVersion=_minimumNewsVersion;
@property(readonly, nonatomic) long long score; // @synthesize score=_score;
@property(readonly, nonatomic) NSArray *pinnedArticleIDs; // @synthesize pinnedArticleIDs=_pinnedArticleIDs;
@property(readonly, nonatomic) NSArray *allowedStorefrontIDs; // @synthesize allowedStorefrontIDs=_allowedStorefrontIDs;
@property(readonly, nonatomic) NSArray *blockedStorefrontIDs; // @synthesize blockedStorefrontIDs=_blockedStorefrontIDs;
@property(readonly, nonatomic) NSArray *iAdCategories; // @synthesize iAdCategories=_iAdCategories;
@property(readonly, nonatomic) NSArray *relatedChannelIDsForOnboarding; // @synthesize relatedChannelIDsForOnboarding=_relatedChannelIDsForOnboarding;
@property(readonly, nonatomic) NSArray *relatedTopicIDsForOnboarding; // @synthesize relatedTopicIDsForOnboarding=_relatedTopicIDsForOnboarding;
@property(readonly, nonatomic) NSArray *relatedChannelIDs; // @synthesize relatedChannelIDs=_relatedChannelIDs;
@property(readonly, nonatomic) NSArray *relatedTopicIDs; // @synthesize relatedTopicIDs=_relatedTopicIDs;
@property(readonly, copy, nonatomic) NSString *replacementID; // @synthesize replacementID=_replacementID;
@property(readonly, copy, nonatomic) NSString *primaryAudience; // @synthesize primaryAudience=_primaryAudience;
@property(readonly, nonatomic) _Bool isExplicitContent; // @synthesize isExplicitContent=_isExplicitContent;
@property(readonly, nonatomic) _Bool isDeprecated; // @synthesize isDeprecated=_isDeprecated;
@property(readonly, nonatomic) _Bool isPublic; // @synthesize isPublic=_isPublic;
@property(readonly, nonatomic) long long contentProvider; // @synthesize contentProvider=_contentProvider;
@property(readonly, nonatomic) unsigned long long tagType; // @synthesize tagType=_tagType;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *versionKey; // @synthesize versionKey=_versionKey;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)ppt_overrideFeedID:(id)arg1;
@property(readonly, nonatomic) long long statusBarStyle;
@property(readonly, nonatomic) UIColor *foregroundColor;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) FCTagBanner *bannerImageForThemeBackground; // @synthesize bannerImageForThemeBackground=_bannerImageForThemeBackground;
@property(readonly, nonatomic) FCTagBanner *bannerImageForWhiteBackground; // @synthesize bannerImageForWhiteBackground=_bannerImageForWhiteBackground;
@property(readonly, nonatomic) FCTagBanner *defaultBannerImage;
@property(readonly, nonatomic) _Bool isWhite;
@property(readonly, nonatomic) FCTagBanner *bannerImageForMask; // @synthesize bannerImageForMask=_bannerImageForMask;
@property(readonly, nonatomic) long long feedType;
- (_Bool)isNoLongerAvailable;
- (id)feedIDsForExploration;
- (id)feedIDForHighlights;
- (id)availableBins;
- (id)feedIDForBin:(long long)arg1;
- (id)_feedIDForBin:(long long)arg1 withFallback:(_Bool)arg2;
- (_Bool)isEqualToTag:(id)arg1;
@property(readonly, nonatomic) _Bool isSubscribable;
@property(readonly, copy, nonatomic) id <FCFeedTheming> theme;
@property(readonly, nonatomic) id <FCTopicProviding> asTopic;
@property(readonly, nonatomic) id <FCSectionProviding> asSection;
@property(readonly, nonatomic) id <FCChannelProviding> asChannel;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initChannelForTestingWithIdentifier:(id)arg1 name:(id)arg2 defaultSection:(id)arg3;
- (id)initForTestingWithTagType:(unsigned long long)arg1 identifier:(id)arg2 name:(id)arg3;
- (void)_inflateFromJSONDictionary:(id)arg1 withVersion:(long long)arg2;
- (void)_inflateFromVersionlessJSONDictionary:(id)arg1;
- (void)_inflateFromJSONDictionary:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSArray *loadableFonts;
- (id)initWithTagRecord:(id)arg1 interestToken:(id)arg2;
- (id)initWithTagType:(unsigned long long)arg1 identifier:(id)arg2 name:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

