//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FCTagFeedCursor, NSArray, NSString;

@interface FCTagFeedResponse : NSObject
{
    _Bool _fulfilledRequest;
    NSString *_tagID;
    NSString *_feedID;
    NSArray *_feedItems;
    FCTagFeedCursor *_topCursor;
    FCTagFeedCursor *_bottomCursor;
}

@property(nonatomic) _Bool fulfilledRequest; // @synthesize fulfilledRequest=_fulfilledRequest;
@property(retain, nonatomic) FCTagFeedCursor *bottomCursor; // @synthesize bottomCursor=_bottomCursor;
@property(retain, nonatomic) FCTagFeedCursor *topCursor; // @synthesize topCursor=_topCursor;
@property(copy, nonatomic) NSArray *feedItems; // @synthesize feedItems=_feedItems;
@property(copy, nonatomic) NSString *feedID; // @synthesize feedID=_feedID;
@property(copy, nonatomic) NSString *tagID; // @synthesize tagID=_tagID;
- (void).cxx_destruct;

@end

