//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCPrivateZoneController.h>

@class NSDate, NSMutableDictionary, NSNumber, NSString;

@interface FCUserInfo : FCPrivateZoneController
{
    NSMutableDictionary *_tagSettingsEntriesByTagID;
}

+ (id)commandsToMergeLocalDataToCloud:(id)arg1;
+ (long long)commandQueueUrgency;
+ (id)commandStoreFileName;
+ (unsigned long long)localStoreVersion;
+ (id)localStoreFilename;
+ (_Bool)requiresHighPriorityFirstSync;
+ (_Bool)requiresBatchedSync;
+ (_Bool)requiresPushNotificationSupport;
+ (id)desiredKeys;
@property(retain, nonatomic) NSMutableDictionary *tagSettingsEntriesByTagID; // @synthesize tagSettingsEntriesByTagID=_tagSettingsEntriesByTagID;
- (void).cxx_destruct;
- (void)handleSyncWithTagSettingsRecord:(id)arg1;
- (void)handleSyncWithUserInfoRecord:(id)arg1;
- (void)handleSyncWithChangedRecords:(id)arg1 deletedRecordIDs:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)loadLocalCachesFromStore;
- (id)fontSizeForTagID:(id)arg1;
- (void)setFontSizeForTagID:(id)arg1 fontSize:(id)arg2;
- (void)syncFontSizeForTagID:(id)arg1;
- (id)_entryIDForTagID:(id)arg1;
@property(readonly, nonatomic) long long personalizationTreatmentID;
@property(copy, nonatomic) NSDate *dateLastOpened;
@property(readonly, nonatomic) _Bool topStoriesIntroductionDisplayed;
@property(copy, nonatomic) NSNumber *firstLaunchVersionNumber;
@property(copy, nonatomic) NSString *feldsparID;
- (void)markTopStoriesIntroductionAsDisplayed;
- (id)initWithContext:(id)arg1 cloudKitConnection:(id)arg2 recordZone:(id)arg3 storeDirectory:(id)arg4;

@end

