//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (FCAdditions)
+ (id)fc_dateWithMillisecondsTimeIntervalSince1970:(unsigned long long)arg1;
- (unsigned long long)fc_millisecondTimeIntervalSince1970;
- (id)fc_dateBySubtractingTimeInterval:(double)arg1;
- (_Bool)fc_isLaterThan:(id)arg1;
- (_Bool)fc_isEarlierThan:(id)arg1;
@property(readonly) double fc_timeIntervalUntilNow;
@end

