//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumber.h>

@interface NSNumber (FCAdditions)
- (_Bool)fc_isGreaterThan:(id)arg1;
- (_Bool)fc_isLessThanOrEqualTo:(id)arg1;
- (_Bool)fc_isLessThan:(id)arg1;
- (id)fc_largerNumber:(id)arg1;
- (id)fc_smallerNumber:(id)arg1;
@end

