//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOrderedSet.h>

#import <NewsCore/FCOrderedCollectionAdditions-Protocol.h>

@interface NSOrderedSet (FCAdditions) <FCOrderedCollectionAdditions>
- (id)fc_orderedSetWithObjectsAtIndexes:(id)arg1;
- (id)fc_orderedSetWithObjectsInRange:(struct _NSRange)arg1;
- (id)fc_indexesOfObjectsInOrderedSet:(id)arg1;
- (id)fc_diffAgainstOrderedSet:(id)arg1;
- (id)fc_diffAgainstSortedOrderedCollection:(id)arg1 usingComparator:(CDUnknownBlockType)arg2;
- (_Bool)fc_isSortedUsingComparator:(CDUnknownBlockType)arg1;
- (void)fc_enumerateObjectsPairwiseUsingBlock:(CDUnknownBlockType)arg1;
@end

