//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsTransport/NTPBTagRecord.h>

@interface NTPBTagRecord (FCAdditions)
- (id)generateCoverImageAssetHandleForURLString:(id)arg1;
- (id)generateCoverImageAssetHandle;
- (id)generateNameImageMaskAssetHandle;
- (id)generateNameImageForDarkBackgroundAssetHandle;
- (id)generateNameImageAssetHandle;
- (id)generateLogoImageAssetHandle;
@end

