//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsTransport/NTPBFeedItem.h>

@class FCInterestToken, NTPBArticleRecord;

@interface NTPBFeedItem (FCFeedItem)
+ (id)feedItemWithArticleRecord:(id)arg1 surfacedBySectionID:(id)arg2 surfacedByChannelID:(id)arg3 surfacedByTopicID:(id)arg4 isPinned:(_Bool)arg5 isTopStory:(_Bool)arg6 isFromFirstQuery:(_Bool)arg7 isFromHiddenFeed:(_Bool)arg8;
+ (id)feedItemWithCKFeedItemAndArticleRecord:(id)arg1 surfacedBySectionID:(id)arg2 surfacedByChannelID:(id)arg3 surfacedByTopicID:(id)arg4 isPinned:(_Bool)arg5 isTopStory:(_Bool)arg6 isFromFirstQuery:(_Bool)arg7 isFromHiddenFeed:(_Bool)arg8;
+ (id)cloudKitKeys;
- (id)description;
@property(retain, nonatomic) FCInterestToken *articleInterestToken;
@property(retain, nonatomic) NTPBArticleRecord *articleRecord;
- (_Bool)isEligibleForClusterFiltering;
- (id)publishDate;
- (double)tileProminenceScore;
- (id)copyWithPersonalizedScore:(double)arg1 featuresScore:(double)arg2;
- (id)lastTopStoryInClusterCopy;
- (id)firstTopStoryInClusterCopy;
- (id)unpinnedCopy;
- (id)pinnedCopy;
- (id)usesImageOnTopLayoutCopy;
- (id)wasFeaturedCopy;
- (id)unfeaturedCopy;
- (id)featuredCopy;
- (_Bool)isArticleOlderThan:(double)arg1;
- (double)globalScoreAtDate:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@end

