//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsTransport/NTPBReadingHistoryItem.h>

#import <NewsCore/FCKeyValueStoreCoding-Protocol.h>
#import <NewsCore/FCReadingHistoryItem-Protocol.h>

@class NSDate, NSString;

@interface NTPBReadingHistoryItem (FCReadingHistory) <FCReadingHistoryItem, FCKeyValueStoreCoding>
+ (id)readValueFromKeyValuePair:(id)arg1;
+ (int)keyValuePairType;
+ (id)readingHistoryItemWithCKRecord:(id)arg1;
- (void)writeToKeyValuePair:(id)arg1;
@property(nonatomic) unsigned long long articleLikingStatus;
@property(nonatomic) _Bool hasArticleBeenConsumed;
@property(nonatomic) _Bool hasArticleBeenMarkedOffensive;
@property(nonatomic) _Bool hasArticleBeenSeen;
@property(nonatomic) _Bool hasArticleBeenRead;
@property(copy, nonatomic) NSDate *lastVisitedAt;
@property(readonly, copy, nonatomic) NSString *identifier;

// Remaining properties
@property(copy, nonatomic) NSString *articleID;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

