//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (TextInfoAdditions)
+ (id)fontFromTextInfo:(id)arg1 forColumnSpan:(long long)arg2 withDefaultFontName:(id)arg3 defaultFontSize:(double)arg4;
@end

